import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { fail, parseFrontmatter, walkFiles } from "./validation-lib.ts";

const pkg = JSON.parse(readFileSync("package.json", "utf8")) as {
  pi?: Record<string, string[]>;
  name?: string;
  description?: string;
};

const pi = pkg.pi ?? {};
const lines: string[] = [];

lines.push("<!-- AUTO-GENERATED BY scripts/generate-catalog.ts — DO NOT EDIT MANUALLY -->");
lines.push("");
const title = pkg.name?.split("/").pop() ?? "Catalog";
lines.push(`# ${title}`);
lines.push("");

// Extensions
if (pi.extensions) {
  lines.push("## Extensions");
  lines.push("");
  lines.push("| Name | Path | Purpose |");
  lines.push("| --- | --- | --- |");
  for (const relPath of pi.extensions) {
    const absPath = join(process.cwd(), relPath);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) continue;
    const entries = readdirSync(absPath).filter((e) => statSync(join(absPath, e)).isDirectory());
    for (const name of entries) {
      const indexPath = join(absPath, name, "index.ts");
      const source = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : "";
      // Find the first top-level description property line.
      // The ^ anchor with 'm' flag matches only at line starts,
      // so it won't match description: inside nested calls like Type.String({ description: ... }).
      const descMatch = source.match(/^\s*description:\s*["']([^"']+)["']/m);
      const description = descMatch?.[1]?.trim() ?? "No description found.";
      lines.push(`| ${name} | \`${relPath}/${name}\` | ${description} |`);
    }
  }
  lines.push("");
}

// Skills
if (pi.skills) {
  lines.push("## Skills");
  lines.push("");
  lines.push("| Name | Path | Purpose |");
  lines.push("| --- | --- | --- |");
  for (const relPath of pi.skills) {
    const absPath = join(process.cwd(), relPath);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) continue;
    const skillFiles = walkFiles(absPath, (p) => p.endsWith("SKILL.md"));
    for (const file of skillFiles) {
      const name = file.split("/").filter((_, i, arr) => i === arr.length - 2).pop() ?? "unknown";
      const fm = parseFrontmatter(file);
      const description = fm.description ?? "No description found.";
      lines.push(`| ${name} | \`${relPath}/${name}\` | ${description} |`);
    }
  }
  lines.push("");
}

// Prompts
if (pi.prompts) {
  lines.push("## Prompt templates");
  lines.push("");
  lines.push("| Command | Path | Purpose |");
  lines.push("| --- | --- | --- |");
  for (const relPath of pi.prompts) {
    const absPath = join(process.cwd(), relPath);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) continue;
    const promptFiles = walkFiles(absPath, (p) => p.endsWith(".md"));
    for (const file of promptFiles) {
      const fm = parseFrontmatter(file);
      const command = fm.name ?? file.split("/").pop()?.replace(".md", "") ?? "unknown";
      const description = fm.description ?? "No description found.";
      lines.push(`| \`${command}\` | \`${relPath}/${file.split("/").pop()}\` | ${description} |`);
    }
  }
  lines.push("");
}

// Themes
if (pi.themes) {
  lines.push("## Themes");
  lines.push("");
  lines.push("| Name | Path | Purpose |");
  lines.push("| --- | --- | --- |");
  for (const relPath of pi.themes) {
    const absPath = join(process.cwd(), relPath);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) continue;
    const themeFiles = walkFiles(absPath, (p) => p.endsWith(".json"));
    for (const file of themeFiles) {
      try {
        const theme = JSON.parse(readFileSync(file, "utf8")) as {
          name?: string;
          vars?: Record<string, unknown>;
          colors?: Record<string, unknown>;
        };
        const name = theme.name ?? file.split("/").pop()?.replace(".json", "") ?? "unknown";
        const varCount = theme.vars ? Object.keys(theme.vars).length : 0;
        const colorCount = theme.colors ? Object.keys(theme.colors).length : 0;
        const description = `${varCount} vars, ${colorCount} colors`;
        lines.push(`| ${name} | \`${relPath}/${file.split("/").pop()}\` | ${description} |`);
      } catch {
        // Skip invalid JSON
      }
    }
  }
  lines.push("");
}

const output = lines.join("\n") + "\n";

// Output to stdout and also write to file
process.stdout.write(output);
