#!/usr/bin/env python3
"""Regenerate hivesmith's centralized aggregate files from per-PR sources.

Aggregates regenerated:
  - CHANGELOG.md `[Unreleased]` body  ←  .changesets/*.md
  - docs/product-specs/index.md       ←  docs/product-specs/*.md frontmatter
  - docs/exec-plans/tech-debt-tracker.md  ←  .tech-debt/*.md

Single Python process parses every source in one pass — no per-file subprocess
fork. Scales to N=500 specs in well under 1s on CI runners.

Stdlib only. The YAML frontmatter we accept is the flat-scalar subset
(`key: value` per line, optionally quoted) — sufficient for hivesmith's spec /
changeset / tech-debt shapes, no external dep needed.

Usage:
  regen-generated.py                  # regenerate all aggregates in place
  regen-generated.py --check          # exit non-zero if any aggregate would change
  regen-generated.py --release X.Y.Z  # promote [Unreleased] body to stamped X.Y.Z section
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
CHANGESET_DIR = REPO_ROOT / ".changesets"
SPECS_DIR = REPO_ROOT / "docs" / "product-specs"
TECH_DEBT_DIR = REPO_ROOT / ".tech-debt"
CHANGELOG = REPO_ROOT / "CHANGELOG.md"
SPECS_INDEX = SPECS_DIR / "index.md"
TECH_DEBT_TRACKER = REPO_ROOT / "docs" / "exec-plans" / "tech-debt-tracker.md"

CHANGESET_TYPES = ["added", "changed", "fixed", "removed", "deprecated", "security"]
STAGES = ["TRIAGE", "RESEARCH", "PLAN", "IMPLEMENT", "REVIEW", "GATE", "DONE", "REJECTED"]
ACTIVE_STAGES = {"TRIAGE", "RESEARCH", "PLAN", "IMPLEMENT", "REVIEW", "GATE"}
PRIORITY_ORDER = {"P1": 1, "P2": 2, "P3": 3}

DRY_RUN = False  # set by --check; suppresses all writes in _write_if_changed

GENERATED_HEADER = "<!-- generated by scripts/regen-generated.py — do not edit by hand. Source: docs/product-specs/*.md frontmatter. -->"


class RegenError(Exception):
    """Raised for unrecoverable source errors. Message goes to stderr; exit 1."""


# ---------- frontmatter -----------------------------------------------------

_FRONT_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)


def _coerce_scalar(raw: str) -> Any:
    """Cast a YAML-ish scalar to int / bool / None / str. Flat-scalar subset only."""
    s = raw.strip()
    if not s:
        return ""
    # Quoted strings: keep contents verbatim.
    if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
        return s[1:-1]
    low = s.lower()
    if low in ("true", "false"):
        return low == "true"
    if low in ("null", "~"):
        return None
    # Integer (no leading-zero special-cases — issue numbers, PR numbers).
    if re.fullmatch(r"-?\d+", s):
        try:
            return int(s)
        except ValueError:
            pass
    # Everything else is a string. Dates stay as strings; downstream code only
    # uses them for display / sort, so the lexicographic order matches ISO order.
    return s


def split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Parse the leading '---'-delimited frontmatter block. Flat scalars only.

    Lines that don't look like 'key: value' (after the opening '---') are an
    error — we want loud failures during the migration, not silent drops.
    Blank lines and lines starting with '#' are skipped.
    """
    m = _FRONT_RE.match(text)
    if not m:
        return {}, text
    data: dict[str, Any] = {}
    for line_no, raw_line in enumerate(m.group(1).splitlines(), start=1):
        line = raw_line.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise RegenError(f"frontmatter line {line_no}: expected 'key: value', got: {raw_line!r}")
        key, _, value = line.partition(":")
        key = key.strip()
        if not key:
            raise RegenError(f"frontmatter line {line_no}: empty key")
        # Strip inline `# comment` from values (YAML semantics). A bare `#`
        # inside a quoted string is not a comment, so only strip when the
        # value isn't quoted — quoted strings are detected in _coerce_scalar.
        stripped_value = value.strip()
        if not (stripped_value.startswith(('"', "'"))):
            comment_idx = stripped_value.find(" #")
            if comment_idx == -1 and stripped_value.startswith("#"):
                comment_idx = 0
            if comment_idx >= 0:
                value = stripped_value[:comment_idx]
        data[key] = _coerce_scalar(value)
    return data, m.group(2)


def load_all(directory: Path, glob: str = "*.md", exclude: set[str] | None = None) -> list[tuple[Path, dict[str, Any], str]]:
    """Load frontmatter + body for every matching file in a directory.

    One Python process; one pass; no per-file subprocess fork.
    """
    if not directory.exists():
        return []
    exclude = exclude or set()
    out: list[tuple[Path, dict[str, Any], str]] = []
    for path in sorted(directory.glob(glob)):
        if path.name in exclude:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise RegenError(f"cannot read {path}: {exc}") from exc
        try:
            data, body = split_frontmatter(text)
        except RegenError as exc:
            raise RegenError(f"{path}: {exc}") from exc
        out.append((path, data, body))
    return out


# ---------- changesets → CHANGELOG ------------------------------------------


def validate_changeset(path: Path, fm: dict[str, Any]) -> None:
    # `issue` is optional — historical / migrated entries may not have one.
    missing = [k for k in ("type", "bump") if k not in fm]
    if missing:
        raise RegenError(f"{path}: missing required frontmatter keys: {', '.join(missing)}")
    if fm["type"] not in CHANGESET_TYPES:
        raise RegenError(f"{path}: invalid type '{fm['type']}'. Must be one of: {', '.join(CHANGESET_TYPES)}")
    if fm["bump"] not in ("major", "minor", "patch", "none"):
        raise RegenError(f"{path}: invalid bump '{fm['bump']}'. Must be major | minor | patch | none")


def render_changeset_body(changesets: list[tuple[Path, dict[str, Any], str]]) -> str:
    """Render the body that goes between '## [Unreleased]' and the next '## ['."""
    if not changesets:
        return "\n"
    by_type: dict[str, list[str]] = {t: [] for t in CHANGESET_TYPES}
    for path, fm, body in changesets:
        validate_changeset(path, fm)
        # body is appended verbatim, stripped of leading/trailing blank lines
        cleaned = body.strip("\n")
        if not cleaned:
            raise RegenError(f"{path}: empty changeset body")
        by_type[fm["type"]].append(cleaned)
    out: list[str] = [""]
    for t in CHANGESET_TYPES:
        if not by_type[t]:
            continue
        out.append(f"### {t.capitalize()}")
        for entry in by_type[t]:
            out.append(entry)
        out.append("")
    # Drop the final trailing blank — the regex re-attaches `\n## [` after,
    # so an extra blank here would render as a double blank line in CHANGELOG.
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


_UNRELEASED_RE = re.compile(
    r"(## \[Unreleased\][^\n]*\n)(.*?)(\n## \[)",
    re.DOTALL,
)

# Fallback when there's no prior released section (fresh project scaffold).
# Capture from `## [Unreleased]` to end-of-document, optionally stopping at the
# Keep-a-Changelog link reference block (lines like `[Unreleased]: …`).
_UNRELEASED_TAIL_RE = re.compile(
    r"(## \[Unreleased\][^\n]*\n)(.*?)(\n\[Unreleased\]:|\Z)",
    re.DOTALL,
)


def rewrite_unreleased_body(changelog_text: str, new_body: str) -> str:
    m = _UNRELEASED_RE.search(changelog_text)
    if m:
        return changelog_text[: m.start(2)] + new_body + changelog_text[m.end(2) :]
    # Fresh project: no prior `## [VERSION]` section yet. Replace from
    # `## [Unreleased]` up to the link-reference block (or EOF).
    m = _UNRELEASED_TAIL_RE.search(changelog_text)
    if not m:
        raise RegenError("CHANGELOG.md has no '## [Unreleased]' section")
    return changelog_text[: m.start(2)] + new_body + changelog_text[m.end(2) :]


def promote_unreleased_to_version(changelog_text: str, version: str, date: str) -> str:
    """Move current [Unreleased] body into a new ## [version] — date section."""
    m = _UNRELEASED_RE.search(changelog_text)
    if not m:
        # Fresh project case: no prior released section. Use the tail fallback.
        m = _UNRELEASED_TAIL_RE.search(changelog_text)
        if not m:
            raise RegenError("CHANGELOG.md has no '## [Unreleased]' section")
    unreleased_body = m.group(2).strip("\n")
    if not unreleased_body:
        raise RegenError(f"refusing to release {version}: [Unreleased] body is empty")
    # Aim for exactly one blank line between sections. Group 1 ends with
    # `## [Unreleased]\n`; group 3 begins with `\n## [previous]`. The new
    # body inserted between them needs to be `\n## [VERSION] — DATE\n\n<body>\n`
    # so the final layout is `## [Unreleased]\n\n## [VERSION] — DATE\n\n<body>\n\n## [previous]`.
    new_body = f"\n## [{version}] — {date}\n\n{unreleased_body}\n"
    return changelog_text[: m.start(2)] + new_body + changelog_text[m.end(2) :]


def regen_changelog(release_version: str | None = None) -> bool:
    """Returns True if the file changed on disk."""
    text = CHANGELOG.read_text(encoding="utf-8")
    changesets = load_all(CHANGESET_DIR)
    # Skip the README and .gitkeep stubs — they have no frontmatter.
    changesets = [(p, fm, body) for (p, fm, body) in changesets if fm]
    new_body = render_changeset_body(changesets)
    new_text = rewrite_unreleased_body(text, new_body)
    if release_version:
        today = dt.date.today().isoformat()
        new_text = promote_unreleased_to_version(new_text, release_version, today)
    return _write_if_changed(CHANGELOG, new_text)


# ---------- specs → index.md ------------------------------------------------


def validate_spec(path: Path, fm: dict[str, Any]) -> None:
    # `issue` is optional — specs created locally (without a GitHub issue) carry
    # no issue number; the index renders `—` for them. Required: title, stage.
    missing = [k for k in ("title", "stage") if k not in fm]
    if missing:
        raise RegenError(f"{path}: missing required frontmatter keys: {', '.join(missing)}")
    if fm["stage"] not in STAGES:
        raise RegenError(f"{path}: invalid stage '{fm['stage']}'. Must be one of: {', '.join(STAGES)}")
    if fm["stage"] == "REJECTED" and not fm.get("rejection_reason"):
        raise RegenError(f"{path}: stage=REJECTED requires rejection_reason")
    if fm["stage"] == "DONE" and not fm.get("shipped"):
        raise RegenError(f"{path}: stage=DONE requires shipped (ISO date)")


def _shipped_key(fm: dict[str, Any]) -> str:
    val = fm.get("shipped", "")
    return str(val) if val else ""


def render_index(specs: list[tuple[Path, dict[str, Any], str]]) -> str:
    active: list[dict[str, Any]] = []
    completed: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    for path, fm, _ in specs:
        validate_spec(path, fm)
        slug = path.stem
        row = {**fm, "slug": slug}
        if fm["stage"] in ACTIVE_STAGES:
            active.append(row)
        elif fm["stage"] == "DONE":
            completed.append(row)
        elif fm["stage"] == "REJECTED":
            rejected.append(row)
    def _issue_sort_key(r: dict[str, Any]) -> int:
        v = r.get("issue")
        try:
            return int(v) if v is not None else 9_999_999
        except (TypeError, ValueError):
            return 9_999_999

    active.sort(key=lambda r: (PRIORITY_ORDER.get(r.get("priority", "P3"), 9), _issue_sort_key(r)))
    completed.sort(key=lambda r: _shipped_key(r), reverse=True)
    rejected.sort(key=_issue_sort_key)

    lines: list[str] = [
        GENERATED_HEADER,
        "",
        "# Product specs",
        "",
        "The *what* and *why* of work this project plans to do. Each spec describes user value, success criteria, and explicit non-goals. The *how* lives in `docs/exec-plans/`.",
        "",
        "## Active",
        "",
        "| Priority | Issue | Title | Stage | Spec |",
        "|----------|-------|-------|-------|------|",
    ]
    if not active:
        lines.append("| — | — | _no active specs_ | — | — |")
    for r in active:
        lines.append(
            f"| {r.get('priority', '—')} | {('#' + str(r['issue'])) if r.get('issue') is not None else '—'} | {r['title']} | {r['stage']} | [{r['slug']}]({r['slug']}.md) |"
        )
    lines += [
        "",
        "## Completed",
        "",
        "| Issue | Title | PR | Shipped | Spec |",
        "|-------|-------|----|---------|------|",
    ]
    if not completed:
        lines.append("| — | _no completed specs_ | — | — | — |")
    for r in completed:
        pr = f"#{r['pr']}" if r.get("pr") else "—"
        issue_cell = f"#{r['issue']}" if r.get("issue") is not None else "—"
        lines.append(
            f"| {issue_cell} | {r['title']} | {pr} | {r.get('shipped', '—')} | [{r['slug']}]({r['slug']}.md) |"
        )
    lines += [
        "",
        "## Rejected",
        "",
        "| Issue | Title | Reason |",
        "|-------|-------|--------|",
    ]
    if not rejected:
        lines.append("| — | _no rejected specs_ | — |")
    for r in rejected:
        issue_cell = f"#{r['issue']}" if r.get("issue") is not None else "—"
        lines.append(
            f"| {issue_cell} | {r['title']} | {r.get('rejection_reason', '—')} |"
        )
    lines += [
        "",
        "## Conventions",
        "",
        "- This file is **generated** from each spec's YAML frontmatter by `scripts/regen-generated.py`. Edit the spec, not this index.",
        "- `stage:` in the spec's frontmatter is the sole source of truth. Exec plans do not carry a Stage line.",
        "- Canonical lifecycle: `TRIAGE → RESEARCH → PLAN → IMPLEMENT → REVIEW → GATE → DONE`. `REVIEW` = PR open, `/review-loop` driving convergence. `GATE` = review converged, `/merge-gate` validating the still-open PR against the spec. `DONE` = gate verdict PASS recorded and the plan moved to `completed/`; the merge is a separate later step, so a spec can be DONE while its PR is still open.",
        "- A spec is created in TRIAGE and lives forever (it is the historical record of *why we built it*). The exec plan moves to `docs/exec-plans/completed/` on gate PASS, inside the feature PR; the spec stays put.",
        "- `feature-next` reads from the Active list above, ordered by priority.",
        "",
    ]
    return "\n".join(lines)


def regen_specs_index() -> bool:
    specs = load_all(SPECS_DIR, exclude={"index.md", "_template.md"})
    # Drop any spec that has no frontmatter at all (during migration; CI will eventually require it).
    specs = [(p, fm, body) for (p, fm, body) in specs if fm]
    new_text = render_index(specs)
    return _write_if_changed(SPECS_INDEX, new_text)


# ---------- tech debt -------------------------------------------------------


def validate_tech_debt(path: Path, fm: dict[str, Any]) -> None:
    missing = [k for k in ("item", "severity") if k not in fm]
    if missing:
        raise RegenError(f"{path}: missing required frontmatter keys: {', '.join(missing)}")
    if fm["severity"] not in ("low", "med", "high"):
        raise RegenError(f"{path}: invalid severity '{fm['severity']}'. Must be low | med | high")


_TECH_DEBT_HEADER = (
    "<!-- generated by scripts/regen-generated.py — do not edit by hand. Source: .tech-debt/*.md frontmatter. -->\n"
    "# Tech debt tracker\n"
    "\n"
    "Known shortcuts, deferrals, and rough edges. One row per item. Keep entries short — link to the exec plan that introduced or will resolve the debt.\n"
    "\n"
    "| Item | Surfaced in | Severity | Owner | Notes |\n"
    "|------|-------------|----------|-------|-------|\n"
)

_TECH_DEBT_FOOTER = (
    "\n"
    "## Conventions\n"
    "\n"
    "- This file is **generated** from `.tech-debt/*.md` frontmatter by `scripts/regen-generated.py`. Add a row by creating a new `.tech-debt/<id>.md`.\n"
    "- Add an entry whenever an exec plan accepts a known shortcut. Linking back from the plan is required.\n"
    "- `gc-sweep` may add entries automatically when it detects a deviation it can't safely auto-refactor.\n"
    "- Resolve an entry by deleting its source file in the same PR that pays the debt; the commit message is the audit trail.\n"
)


def regen_tech_debt() -> bool:
    entries = load_all(TECH_DEBT_DIR)
    entries = [(p, fm, body) for (p, fm, body) in entries if fm]
    rows: list[str] = []
    for path, fm, _ in entries:
        validate_tech_debt(path, fm)
        rows.append(
            f"| {fm['item']} | {fm.get('surfaced_in', '—')} | {fm['severity']} | {fm.get('owner', 'unowned')} | {fm.get('notes', '—')} |"
        )
    if not rows:
        rows.append("| — | _no tracked debt_ | — | — | — |")
    new_text = _TECH_DEBT_HEADER + "\n".join(rows) + "\n" + _TECH_DEBT_FOOTER
    return _write_if_changed(TECH_DEBT_TRACKER, new_text)


# ---------- io --------------------------------------------------------------


def _write_if_changed(path: Path, new_text: str) -> bool:
    """Write `new_text` to `path` unless unchanged. Returns True if it differed.

    Under DRY_RUN the comparison still happens but nothing is written — this is
    what makes `--check` genuinely read-only.
    """
    if not path.exists() or path.read_text(encoding="utf-8") != new_text:
        if not DRY_RUN:
            path.write_text(new_text, encoding="utf-8")
        return True
    return False


# ---------- main ------------------------------------------------------------


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument("--check", action="store_true", help="exit non-zero if any aggregate would change (read-only)")
    p.add_argument("--release", metavar="VERSION", help="promote [Unreleased] body to a stamped section")
    args = p.parse_args(argv)

    if args.check and args.release:
        sys.stderr.write("--check and --release are mutually exclusive\n")
        return 2

    targets = [
        ("CHANGELOG.md", lambda: regen_changelog(args.release)),
        ("docs/product-specs/index.md", regen_specs_index),
        ("docs/exec-plans/tech-debt-tracker.md", regen_tech_debt),
    ]

    try:
        if args.check:
            # Read-only: render every aggregate and compare in memory. Nothing
            # is written, so an interrupted --check cannot leave a modified tree.
            global DRY_RUN
            DRY_RUN = True
            drifted = []
            for label, fn in targets:
                if fn():
                    drifted.append(label)
            if drifted:
                sys.stderr.write("regen-generated: --check detected drift in: " + ", ".join(drifted) + "\n")
                return 1
            return 0
        else:
            changed_any = False
            for _, fn in targets:
                if fn():
                    changed_any = True
            if changed_any:
                sys.stderr.write("regen-generated: aggregates updated\n")
            else:
                sys.stderr.write("regen-generated: no changes\n")
            return 0
    except RegenError as exc:
        sys.stderr.write(f"regen-generated: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
